import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import WhatsAppButton from "@/components/WAButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const EB = Playfair_Display({
  variable: "--font-eb",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="">
      <body className={`${EB.variable} antialiased`}>
        {/* <Navbar />
        <Header */}
        <Header />
        {children}
        <WhatsAppButton />
        <Toaster position="top-center" toastOptions={{ duration: 3000 }} />

        <Footer />
      </body>
    </html>
  );
}
